imports:
    - { resource: parameters.ini }
    - { resource: security.yml }
    - { resource: session.yml }

framework:
    #esi:             ~
    #translator:      { fallback: en }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: false
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8

            eayso:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_eayso_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8

            osso2007:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_osso2007_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8

            osso2012:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_osso2012_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8

    orm:
        default_entity_manager:   default
        auto_generate_proxy_classes: %kernel.debug%
#       auto_mapping: true
        entity_managers:
            default:
                connection: default
                mappings:
                    Osso2007Bundle: ~
            eayso:
                connection: eayso
                mappings:
                    EaysoBundle: ~
            osso2007:
                connection: osso2007
                mappings:
                    Osso2007Bundle: ~
            osso2012:
                connection: osso2012
                mappings:
                    Osso2007Bundle: ~
        
#      auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

services:
    game.managerx:
        class:        Zayso\Osso2007Bundle\Service\GameManager
        arguments:    [@doctrine.orm.entity_manager]
