
zayso_core_index:
    pattern:  /
    defaults: { _controller: ZaysoCoreBundle:Public:index }
    
zayso_core_public:
    pattern:  /public
    defaults: { _controller: ZaysoCoreBundle:Public:index }

zayso_core_welcome:
    pattern:  /public/welcome
    defaults: { _controller: ZaysoCoreBundle:Public:index }

# =========================================================
# Account oriented routines
zayso_core_account_signin_check:
    pattern:  /public/account/signin/check
    defaults: { _controller: ZaysoCoreBundle:Account/Signin:check }
    
zayso_core_account_signout:
    pattern:  /public/account/signout
    defaults: { _controller: ZaysoCoreBundle:Account/Signin:signout }
  
 