
zayso_core_index:
    pattern:  /
    defaults: { _controller: ZaysoCoreBundle:Public:index }
    
zayso_core_public:
    pattern:  /public
    defaults: { _controller: ZaysoCoreBundle:Public:index }

zayso_core_welcome:
    pattern:  /public/welcome
    defaults: { _controller: ZaysoCoreBundle:Public:index }

#
# This will grab anything that falls through though I think it might need to be moved to it's own file
# Just to ensure it is loaded after all other routes
zayso_core_unknown:
    pattern:  /{url}
    defaults: { _controller: ZaysoCoreBundle:Public:index, url: "unknown" }
    requirements:
        url: ".+"
 