services:
  
    zayso_core.schedule.referee.search.formtype:
        class: Zayso\CoreBundle\FormType\Schedule\RefSearchFormType
        arguments: ["@zayso_core.schedule.manager"]
        tags:
            - { name: form.type, alias: ref_sch_search }
            
    zayso_core.schedule.referee.assign.formtype:
        class: Zayso\CoreBundle\FormType\Schedule\RefAssignFormType
        arguments: ["@zayso_core.schedule.manager"]
        tags:
            - { name: form.type, alias: ref_sch_assign }
            
    zayso_core.person.team.list.formtype:
        class: Zayso\CoreBundle\FormType\Person\TeamListFormType
        arguments: ['@zayso_core.person.manager', %zayso_core.project.master%]
        tags:
            - { name: form.type, alias: ref_sch_assign }
            
    zayso_core.misc.datex.formtype:
        class: Zayso\CoreBundle\FormType\Misc\DatexFormType
        arguments: ["@zayso_core.schedule.manager"]
        tags:
            - { name: form.type, alias: datex }
  
    zayso_core.account.signin.formtype:
        class: Zayso\CoreBundle\FormType\Account\SigninFormType
        arguments: ["@zayso_core.account.manager"]
        
    zayso_core.account.edit.formtype:
        class: Zayso\CoreBundle\FormType\Account\EditFormType
        arguments: ["@zayso_core.account.manager"]
        
    zayso_core.account.create.formtype:
        class: Zayso\CoreBundle\FormType\Account\CreateFormType
        arguments: ["@zayso_core.account.manager"]
        
    zayso_core.user_name.validator:
        class: Zayso\CoreBundle\Constraint\UserNameValidator
        arguments: ["@zayso_core.account.manager","@security.context"]
        tags:
            - { name: validator.constraint_validator, alias: user_name }   
            
    zayso_core.person.edit.formtype:
        class: Zayso\CoreBundle\FormType\Person\EditFormType
        arguments: ["@zayso_core.person.manager"]
        tags:
            - { name: form.type, alias: person_edit }
            
    zayso_core.phone.edit.formtype:
        class: Zayso\CoreBundle\FormType\Misc\PhoneFormType
        arguments: ["@zayso_core.person.manager"]
        tags:
            - { name: form.type, alias: phone_edit }
            
    zayso_core.ayso.vol.formtype:
        class: Zayso\CoreBundle\FormType\AYSO\VolFormType
        arguments: ["@zayso_core.person.manager"]
        tags:
            - { name: form.type, alias: zayso_core_ayso_vol }
            
    zayso_core.ayso.region.formtype:
        class: Zayso\CoreBundle\FormType\AYSO\RegionFormType
        arguments: ["@zayso_core.person.manager"]
        tags:
            - { name: form.type, alias: zayso_core_ayso_region }
            
    zayso_core.ayso.vol_id.formtype:
        class: Zayso\CoreBundle\FormType\AYSO\VolIDFormType
        arguments: ["@zayso_core.person.manager"]
        tags:
            - { name: form.type, alias: zayso_core_ayso_vol_id }
            