# Zayso\ArbiterBundle\Resources\config\routine.yml

zayso_arbiter_index:
    pattern:  /
    defaults: { _controller: ZaysoArbiterBundle:Welcome:welcome }

zayso_arbiter_welcome:
    pattern:  /welcome
    defaults: { _controller: ZaysoArbiterBundle:Welcome:welcome }
    
zayso_arbiter_ref_avail:
    pattern:  /referee/availability
    defaults: { _controller: ZaysoArbiterBundle:RefAvail:index }
    
zayso_arbiter_tourn_opencup:
    pattern:  /tourn/opencup
    defaults: { _controller: ZaysoArbiterBundle:Tourn\OpenCup:signup }
    
zayso_arbiter_tourn_kicks:
    pattern:  /tourn/kicks
    defaults: { _controller: ZaysoArbiterBundle:Tourn\Kicks:signup }
