parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     symfony
    database_user:     impd
    database_password: impd894
    
    database_osso2012_name: osso2012y

    session.dsn:      "mysql:dbname=session;host=localhost"

    mailer_transport:  gmail
    mailer_host:       localhost
    mailer_user:       ahundiak@zayso.org
    mailer_password:   qweasd999
    mailer_enabled:    true

    locale:            en
    secret:            zaysoAreaSecretToken
    
    my_bundle_name:    ZaysoAreaBundle
    my_title_prefix:   ZaysoArea5C

    zayso_core.project.master:  70
    zayso_core.project.current: 78

    zayso_core.provider.key:    secured_area
