
zayso_core_index:
    pattern:  /
    defaults: { _controller: ZaysoAreaBundle:Public:index }

zayso_core_welcome:
    pattern:  /public/welcome
    defaults: { _controller: ZaysoAreaBundle:Public:index }
    
# ================================================
# These requires user access
zayso_core_home:
    pattern:  /user/home
    defaults: { _controller: ZaysoAreaBundle:Home:home }
    
zayso_core_person_edit:
    pattern:  /user/person/edit
    defaults: { _controller: ZaysoAreaBundle:Person/Person:edit }
   
# ================================================
# These require admin access
zayso_core_admin:
    pattern:  /admin
    defaults: { _controller: ZaysoCoreBundle:Admin/Admin:index }
    
zayso_core_admin_index:
    pattern:  /admin/index
    defaults: { _controller: ZaysoCoreBundle:Admin/Admin:index }
