zayso_area_index:
    pattern:  /
    defaults: { _controller: ZaysoAreaBundle:Welcome:welcome }

zayso_area_welcome:
    pattern:  /welcome
    defaults: { _controller: ZaysoAreaBundle:Welcome:welcome }

zayso_area_home:
    pattern:  /home
    defaults: { _controller: ZaysoAreaBundle:Welcome:home }
    
zayso_area_contact:
    pattern:  /contact
    defaults: { _controller: ZaysoAreaBundle:Welcome:contact }

zayso_area_account_signin_rpx:
    pattern:  /account/signin/rpx
    defaults: { _controller: ZaysoAreaBundle:Account\Signin:rpx }
    
zayso_area_account_signout:
    pattern:  /account/signout
    defaults: { _controller: ZaysoAreaBundle:Account\Signin:signout }

zayso_area_account_create:
    pattern:  /account/create
    defaults: { _controller: ZaysoAreaBundle:Account\Create:create }
    
zayso_area_account_legacy_profile:
    pattern:  /account/legacy/profile
    defaults: { _controller: ZaysoAreaBundle:Account\Legacy:profile }

zayso_area_account_legacy_signin:
    pattern:  /account/legacy/signin
    defaults: { _controller: ZaysoAreaBundle:Account\Legacy:signin }

zayso_area_schedule_referee_list:
    pattern:  /schedule/referee/list
    defaults: { _controller: ZaysoAreaBundle:Schedule\RefSched:list }

zayso_area_schedule_referee_assign:
    pattern:  /schedule/referee/assign/{id}/{pos}
    defaults: { _controller: ZaysoAreaBundle:Schedule\RefAssign:assign, id: 0, pos: ''}
    requirements:
        id: \d+
        
zayso_area_schedule_game_edit:
    pattern:  /schedule/game/edit/{id}
    defaults: { _controller: ZaysoAreaBundle:Schedule\Game:edit}
    requirements:
        id: \d+
        
zayso_area_admin:
    pattern:  /admin
    defaults: { _controller: ZaysoAreaBundle:Admin\Index:index }
    
zayso_area_admin_import:
    pattern:  /admin/import
    defaults: { _controller: ZaysoAreaBundle:Admin\Import:index }
    
zayso_area_admin_account_edit:
    pattern:  /admin/account/edit/{id}
    defaults: { _controller: ZaysoAreaBundle:Admin\Account\Edit:edit, id: 0}
    requirements:
        id: \d+

zayso_area_admin_account_list:
    pattern:  /admin/account/list.{_format}
    defaults: { _controller: ZaysoAreaBundle:Admin\Account\List:list, _format: html }
    requirements:
        _method:  GET
        _format:  html|csv
        
zayso_area_admin_team_edit:
    pattern:  /admin/team/edit/{id}
    defaults: { _controller: ZaysoAreaBundle:Admin\Team\Edit:edit, id: 0}
    requirements:
        id: \d+

zayso_area_admin_team_list:
    pattern:  /admin/team/list.{_format}
    defaults: { _controller: ZaysoAreaBundle:Admin\Team\List:list, _format: html }
    requirements:
        _method:  GET
        _format:  html|csv
