
zayso_core_index:
    pattern:  /
    defaults: { _controller: ZaysoCoreBundle:Public:index }

zayso_core_welcome:
    pattern:  /public/welcome
    defaults: { _controller: ZaysoCoreBundle:Public:index }
    
zayso_core_welcome_legacy:
    pattern:  /welcome
    defaults: { _controller: ZaysoCoreBundle:Public:index }
    
zayso_core_access_denied:
    pattern:  /public/denied
    defaults: { _controller: ZaysoCoreBundle:Public:denied }
    
zayso_core_access_denied2:
    pattern:  /public/denied2
    defaults: { _controller: ZaysoCoreBundle:Public:denied2 }

# =========================================================
# Account oriented routines
zayso_core_account_signin_check:
    pattern:  /public/account/signin/check
    defaults: { _controller: ZaysoCoreBundle:Account/Signin:check }
    
zayso_core_account_signout:
    pattern:  /public/account/signout
    defaults: { _controller: ZaysoCoreBundle:Account/Signin:signout }
  
zayso_core_account_signin_rpx:
    pattern:  /public/account/signin/rpx
    defaults: { _controller: ZaysoCoreBundle:Account/Signin:rpx }
    
zayso_core_account_edit:
    pattern:  /user/account/edit/{id}
    defaults: { _controller: ZaysoCoreBundle:Account/Edit:edit, id: 0 }
    requirements:
        id: \d+
    
zayso_core_account_openid_add:
    pattern:  /user/account/openid/add
    defaults: { _controller: ZaysoCoreBundle:Account/Openid:add }
    
zayso_core_account_openid_add_rpx:
    pattern:  /user/account/openid/add/rpx
    defaults: { _controller: ZaysoCoreBundle:Account/Openid:addRpx }

# =============================================================
# Person oriented routines
zayso_core_person_edit:
    pattern:  /user/person/edit/{id}
    defaults: { _controller: ZaysoCoreBundle:Person/Edit:edit, id: 0 }
    requirements:
        id: \d+
    
zayso_core_person_team_list:
    pattern:  /user/person/team/list/{personId}
    defaults: { _controller: ZaysoCoreBundle:Person/Team:list, personId: 0 }
    requirements:
        personId: \d+
    
zayso_core_person_person_list:
    pattern:  /user/person/person/list
    defaults: { _controller: ZaysoCoreBundle:Person/PersonPerson:list }
    
# =============================================================
# Schedule items
zayso_core_schedule_referee_list:
    pattern:  /public/schedule/referee/list.{_format}
    defaults: { _controller: ZaysoCoreBundle:Schedule\RefSched:list, _format: html }
    requirements:
        _format:  html|csv|xls|pdf
        
zayso_core_schedule_referee_assign:
    pattern:  /user/schedule/referee/assign/{id}/{pos}
    defaults: { _controller: ZaysoCoreBundle:Schedule\RefAssign:assign, id: 0, pos: ''}
    requirements:
        id: \d+
        
zayso_core_schedule_game_edit:
    pattern:  /user/schedule/game/edit/{id}
    defaults: { _controller: ZaysoCoreBundle:Schedule\GameEdit:edit, id: 0}
    requirements:
        id: \d+
