services:
  
    zayso_core.account.signin.formtype:
        class: Zayso\CoreBundle\FormType\Account\SigninFormType
        arguments: ["@zayso_core.account.manager"]
        
    zayso_core.account.edit.formtype:
        class: Zayso\CoreBundle\FormType\Account\EditFormType
        arguments: ["@zayso_core.account.manager"]
        
    zayso_core.user_name.validator:
        class: Zayso\CoreBundle\Constraint\UserNameValidator
        arguments: ["@zayso_core.account.manager","@security.context"]
        tags:
            - { name: validator.constraint_validator, alias: user_name }        