services:
  
    zayso_core.osso2012.entity_manager:
        alias: doctrine.orm.osso2012_entity_manager
        
    zayso_core.account.manager:
        class: Zayso\CoreBundle\Manager\AccountManager
        arguments: 
            - '@zayso_core.osso2012.entity_manager'
            -  osso2012
            
    zayso_core.project.manager:
        class: Zayso\CoreBundle\Manager\ProjectManager
        arguments: 
            - '@zayso_core.osso2012.entity_manager'
            -  osso2012
        
    zayso_core.user.provider:
        class: Zayso\CoreBundle\User\UserProvider
        arguments: 
            - '@zayso_core.osso2012.entity_manager'
            -  %zayso_core.user.class%
            -  %zayso_core.user.password%
           
    zayso_core.user.password.encoder:
        class: Zayso\CoreBundle\User\UserPasswordEncoder
        arguments: 
            -  %zayso_core.user.password%
          
    zayso_core.user.authentication.provider:
        class: Zayso\CoreBundle\User\UserAuthProvider
        arguments: 
            - '@zayso_core.user.provider'
            -  %zayso_core.provider.key%
            - '@zayso_core.user.password.encoder'
              
    zayso_core.openid.rpx:
        class:  Zayso\CoreBundle\User\OpenidRpx
        scope:  request
        arguments:  
            - '@request'
            -  %zayso_core.openid.rpxApiKey%
            
    zayso_core.session.handler:
        class: Zayso\CoreBundle\Session\SessionHandler
        arguments:  
            - '@zayso_core.session.storage.pdo'
            - %session.storage.db_options%
            - %session.storage.db_options%
            
    zayso_core.session.storage.pdo:
        class:  PDO
        public: false
        arguments:  
            -  %session.dsn%
            -  %database_user%
            -  %database_password%
        