core_routing:
    resource: "@ZaysoCoreBundle/Resources/config/routing.yml"
    
admin_routing:
    resource: "@ZaysoAdminBundle/Resources/config/routing.yml"
    
core_last_routing:
    resource: "@ZaysoCoreBundle/Resources/config/routing_last.yml"
