zayso_area_index:
    pattern:  /
    defaults: { _controller: ZaysoAreaBundle:Welcome:welcome }

zayso_area_welcome:
    pattern:  /welcome
    defaults: { _controller: ZaysoAreaBundle:Welcome:welcome }

zayso_area_account_signin_rpx:
    pattern:  /account/signin/rpx
    defaults: { _controller: ZaysoAreaBundle:Account\Signin:rpx }
    
zayso_area_account_signout:
    pattern:  /account/signout
    defaults: { _controller: ZaysoAreaBundle:Account\Signin:signout }
    
zayso_area_account_legacy_profile:
    pattern:  /account/legacy/profile
    defaults: { _controller: ZaysoAreaBundle:Account\Legacy:profile }