<h1>Section 5 Games - Referee Signup</h1>
<div style="width: 500px">
<p>
If you are a referee then enter the password sent out in the email and press "Login".  
If you just want to browse the schedule without signing up for game then press "Login"
without any password at all.
</p>
<p>For help: Contact <a href="mailto:ahundiak@gmail.com">Art Hundiak</a>. Phone: 256.457.5943</p>
</div>
<form name="login_form" method="post" action="index.php?page=login">
<table width="300" border="0" align="left" cellpadding="0" cellspacing="1" bgcolor="#CCCCCC">
<tr>
<td>
<table width="100%" border="0" cellpadding="3" cellspacing="1" bgcolor="#FFFFFF">
<!--  
<tr>
<td colspan="3"><strong>User Login </strong></td>
</tr>
<tr>
<td width="78">Username</td>
<td width="6">:</td>
<td width="294"><input name="user_name" type="text" id="user_name" value="Public"></td>
</tr>
-->
<tr>
<td>Password</td>
<td>:</td>
<td><input name="user_pass" type="password" id="user_pass"></td>
</tr>
<tr>
<td>&nbsp;</td>
<td>&nbsp;</td>
<td><input type="submit" name="Submit" value="Login"></td>
</tr>
</table>
</td>
</tr>
</table> 
</form>