<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class OSSOFieldItemProxy extends \OSSO\FieldItem implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function getDesc()
    {
        $this->_load();
        return parent::getDesc();
    }

    public function getSiteId()
    {
        $this->_load();
        return parent::getSiteId();
    }

    public function getSite()
    {
        $this->_load();
        return parent::getSite();
    }

    public function something()
    {
        $this->_load();
        return parent::something();
    }

    public function setMe($value)
    {
        $this->_load();
        return parent::setMe($value);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'orgId', 'siteId', 'site', 'desc');
    }
}