# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

_zayso_welcome:
    pattern:  /
    defaults: { _controller: ZaysoBundle:Welcome:welcome }
    
# National Games Routes
_natgames_routing:
    resource: "@NatGamesBundle/Resources/config/routing.yml"

# resource: routing_area5cf.yml
_main:
    resource: routing_area5cf.yml
    
    