# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal


_osso2007_welcome:
    pattern:  /
    defaults: { _controller: Osso2007Bundle:Welcome:legacy }

_osso2007_admin_index:
    pattern:  /admin/index
    defaults: { _controller: Osso2007Bundle:Admin:index }

_osso2007_legacy:
    pattern:  /{cmd}/{action}/{id1}/{id2}
    defaults: { _controller: Osso2007Bundle:Welcome:legacy, cmd: '', action: '', id1: 0, id2: 0 }

_osso2007_account_logout:
    pattern:  /home/logout
    defaults: { _controller: Osso2007Bundle:Welcome:legacy }

_osso2007_account_login:
    pattern:  /home/login
    defaults: { _controller: Osso2007Bundle:Welcome:legacy }

# /
# /account/index
# /account/list

# /home/index
# /home/login
# /home/logout

# /sched_div/list/region#/div#
# /sched_div/list

# /sched_ref/list/region#/div#
# /sched_ref/list
# /sched_ref/signup/id

# /event/edit/id
# /event/edit

# /ref_points/monrovia
# /ref_points/madison

# /admin/index

# /person/list
# /phy_team/list
# /sch_team/list
# /field_site/list
# /unit/list
# /import/proc
# /report/proc



  