Zayso\Osso2007Bundle\Entity\Field:
  type: entity
  table: field
  fields:
    fieldId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: field_id
      generator:
        strategy: IDENTITY
    fieldSiteId:
      type: integer
      unsigned: false
      nullable: true
      column: field_site_id
    unitId:
      type: integer
      unsigned: false
      nullable: true
      column: unit_id
    keyx:
      type: string
      length: 20
      fixed: true
      nullable: true
    sortx:
      type: integer
      unsigned: false
      nullable: true
    descx:
      type: string
      length: 40
      fixed: true
      nullable: true
  lifecycleCallbacks: {  }
