Zayso\Osso2007Bundle\Entity\RefAvail:
  type: entity
  table: ref_avail
  fields:
    refAvailId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: ref_avail_id
      generator:
        strategy: IDENTITY
    groupId:
      type: integer
      unsigned: false
      nullable: true
      column: group_id
    personId:
      type: integer
      unsigned: false
      nullable: true
      column: person_id
    divCrId:
      type: integer
      unsigned: false
      nullable: true
      column: div_cr_id
    divArId:
      type: integer
      unsigned: false
      nullable: true
      column: div_ar_id
    phoneHome:
      type: string
      length: 40
      fixed: true
      nullable: true
      column: phone_home
    phoneWork:
      type: string
      length: 40
      fixed: true
      nullable: true
      column: phone_work
    phoneCell:
      type: string
      length: 40
      fixed: true
      nullable: true
      column: phone_cell
    emailHome:
      type: string
      length: 40
      fixed: true
      nullable: true
      column: email_home
    emailWork:
      type: string
      length: 40
      fixed: true
      nullable: true
      column: email_work
    availDay1:
      type: integer
      unsigned: false
      nullable: true
      column: avail_day1
    availDay2:
      type: integer
      unsigned: false
      nullable: true
      column: avail_day2
    availDay3:
      type: integer
      unsigned: false
      nullable: true
      column: avail_day3
    availDay4:
      type: integer
      unsigned: false
      nullable: true
      column: avail_day4
    availDay5:
      type: integer
      unsigned: false
      nullable: true
      column: avail_day5
    availDay6:
      type: integer
      unsigned: false
      nullable: true
      column: avail_day6
    teamId1:
      type: integer
      unsigned: false
      nullable: true
      column: team_id1
    teamId2:
      type: integer
      unsigned: false
      nullable: true
      column: team_id2
    teamId3:
      type: integer
      unsigned: false
      nullable: true
      column: team_id3
    modified:
      type: string
      length: 16
      fixed: true
      nullable: false
    notes:
      type: string
      length: 1000
      fixed: false
      nullable: false
  lifecycleCallbacks: {  }
