<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>S5Games Referee Signup</title>
<link rel="stylesheet" type="text/css" href="s5games.css" />
</head>
<body id="layout-body">
<div id="layout-page">
<div id="layout-content">
<?php echo $content; ?>
</div>
</div>
</body>
</html>