<?php $game = $tpl->game; ?>
<form name="referee_signup" method="post" action="index.php?page=signup" >

<input type="hidden" name="game_id" value="<?php echo $game->id;   ?>" />
<input type="hidden" name="pos_id"  value="<?php echo $tpl->posId; ?>" />
		       
<table border="1" width="500">
<tr><th colspan="2">Referee Signup Form</th></tr>
<tr>
  <td>Game Info</td>
  <td><?php echo "{$game->id}, {$game->date}, {$game->time}, {$game->div}, {$game->field}"; ?></td>
</tr>
<tr>
  <td>Bracket</td>
  <td><?php echo $game->bracket; ?></td>
</tr>
<tr>
  <td>Home Team</td>
  <td><?php echo $this->escape($game->homeName); ?></td>
</tr>
<tr>
  <td>Away Team</td>
  <td><?php echo $this->escape($game->awayName); ?></td>
</tr>
<tr><td colspan="2"></td></tr>
<?php foreach($tpl->persons as $index => $person) {
    if ($person['name'] || ($index < 3)) {
?>
<tr>
  <td><?php echo $person['pos'];  ?></td>
  <td><?php echo $person['name']; ?></td>
</tr>
<?php }} ?>
<tr><td colspan="2"></td></tr>
<tr>
  <td>Referee Position</td>
  <td>
  <?php
    if (!$tpl->user->isAdmin) echo $tpl->posPickList[$tpl->posId];
    else {
  ?>
    <select name="pos_id">
      <?php echo $this->formOptions($tpl->posPickList,$tpl->posId); ?>
    </select>
	<?php } ?>
  </td>
</tr>
<tr>
  <td>Request Assessment</td>
  <td>
    <select name="referee_ass">
      <option value="0">None</option>
      <?php echo $this->formOptions($tpl->assPickList,$tpl->refAss); ?>
    </select>
  </td>
</tr>
<tr>
  <td>Referee AYSOID</td>
  <td>
    <input type="text" name="referee_aysoid" size="10"
           value="<?php echo $this->escape($tpl->refAysoid); ?>" />
    <input type="submit" name="referee_verify" value="Verify AYSOID" />
  </td>
</tr>
<tr><td colspan="2"></td></tr>
<tr>
  <td>Referee Region</td>
  <td>
    <?php
      if ($tpl->refRegion) echo $tpl->regionPickList[$tpl->refRegion];
    ?>
    <?php /*
    <select name="referee_region">
      <option value="0">Select your region</option>
      <?php echo $this->formOptions($tpl->regionPickList,$tpl->refRegion); ?>
    </select>
     */ ?>
  </td>
</tr>
<tr>
  <td>Referee First Name</td>
  <td>
    <?php echo $this->escape($tpl->refFirstName); ?>
    <?php /*
    <input type="text" name="referee_first_name" size="30" readonly="readonly"
           value="<?php echo $this->escape($tpl->refFirstName); ?>" />
     */ ?>
  </td>
</tr>
<tr>
  <td>Referee Last Name</td>
  <td>
    <?php echo $this->escape($tpl->refLastName); ?>
    <?php /*
    <input type="text" name="referee_last_name" size="30"
           value="<?php echo $this->escape($tpl->refLastName); ?>" />
    */ ?>
  </td>
</tr>
<tr>
  <td>Referee Badge</td>
  <td>
    <?php echo $this->escape($tpl->refBadge); ?>
  </td>
</tr>
<tr><td colspan="2"></td></tr>
<tr>
  <td>Assignment Status</td>
  <td>
    <select name="referee_status">
      <?php echo $this->formOptions($tpl->statusPickList,$tpl->refStatus); ?>
    </select>
  </td>
</tr>
<tr>
  <td><a href="index.php?page=schedule">Return to schedule</a></td>
  <td>
    <input type="submit" name="referee_signup" value="Signup For Game" />
  </td>
</tr>
<?php if ($tpl->errors) { ?>
<tr>
  <td colspan="2" style="color: red">
    <?php foreach($tpl->errors as $error)
    {
      echo $this->escape($error) . "\n<br />";
    }
    ?>
  </td>
</tr>	
<?php }?>
</table>
</form>
<br />
<div style="width: 600px">
<p>
To signup for a game, fill in your 8 digit ayso volunteer id then press "Signup".
Your name will appear in the middle section of the form indicating that the assignment has been accepted
and is pending approval.  Return to the schedule screen and you will see your name in green.  When the
assignor approves your request your name will turn to black.
</p>
<ul>
  <li>Do not sign up for your own child's games.</li>
  <li>Do not sign up for your own region's games.</li>
  <li>Avoid signing up for games in the same division/bracket that your children play in.</li>
</ul>
<p>
If you really do not want to do the game because your schedule is packed but are signing up anyways because
it is required for the tournament then choose the "Ref only if needed" option from the Assignment Status
column.  Your name will show in red on the schedule and other people will be able to take your assignment. 
You are still on the hook to do the game unless your name gets removed from the schedule.
</p><br /><p>
The only way to remove yourself from a game is to contact
<a href="mailto:ahundiak@s5games.org">Art Hundiak</a>. Phone: 256.457.5943
</p>
</div>