Zayso\Osso2007Bundle\Entity\FamilyPerson:
  type: entity
  table: family_person
  fields:
    familyPersonId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: family_person_id
      generator:
        strategy: IDENTITY
    familyId:
      type: integer
      unsigned: false
      nullable: true
      column: family_id
    personId:
      type: integer
      unsigned: false
      nullable: true
      column: person_id
    familyPersonTypeId:
      type: integer
      unsigned: false
      nullable: true
      column: family_person_type_id
  lifecycleCallbacks: {  }
