Zayso\Osso2007Bundle\Entity\PhyTeam:
  type: entity
  table: phy_team
  fields:
    phyTeamId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: phy_team_id
      generator:
        strategy: IDENTITY
    regYearId:
      type: integer
      unsigned: false
      nullable: true
      column: reg_year_id
    seasonTypeId:
      type: integer
      unsigned: false
      nullable: true
      column: season_type_id
    unitId:
      type: integer
      unsigned: false
      nullable: true
      column: unit_id
    divisionId:
      type: integer
      unsigned: false
      nullable: true
      column: division_id
    divisionSeqNum:
      type: integer
      unsigned: false
      nullable: true
      column: division_seq_num
    name:
      type: string
      length: 20
      fixed: true
      nullable: true
    colors:
      type: string
      length: 20
      fixed: true
      nullable: true
    eaysoId:
      type: integer
      unsigned: false
      nullable: true
      column: eayso_id
    eaysoDes:
      type: string
      length: 20
      fixed: true
      nullable: true
      column: eayso_des
  lifecycleCallbacks: {  }
