<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class NatGamesPersonPersonItemProxy extends \NatGames\Person\PersonItem implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function __get($name)
    {
        $this->_load();
        return parent::__get($name);
    }

    public function addReg($reg)
    {
        $this->_load();
        return parent::addReg($reg);
    }

    public function getAysoid()
    {
        $this->_load();
        return parent::getAysoid();
    }

    public function __set($name, $value)
    {
        $this->_load();
        return parent::__set($name, $value);
    }


    public function __sleep()
    {
        return array('__isInitialized__', '_id', '_fname', '_lname', '_nname', '_email', '_phonec', '_verified', '_status', '_orgKey', '_regs', '_members', '_projects');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}