<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class OSSOPersonItemProxy extends \OSSO\PersonItem implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function getFirstName()
    {
        $this->_load();
        return parent::getFirstName();
    }

    public function getLastName()
    {
        $this->_load();
        return parent::getLastName();
    }

    public function getNickName()
    {
        $this->_load();
        return parent::getNickName();
    }

    public function getAysoid()
    {
        $this->_load();
        return parent::getAysoid();
    }

    public function getName()
    {
        $this->_load();
        return parent::getName();
    }

    public function __get($name)
    {
        $this->_load();
        return parent::__get($name);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'fname', 'lname', 'nname', 'aysoid');
    }
}