jms_security_extra:
    secure_all_services: false
    expressions: true

security:
            
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:        ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        my_provider:
            id: zayso_core.user.provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/
            access_denied_url: /public/denied
            anonymous: ~
            form_login:
                login_path:  /public/denied2
           #    check_path:  /public/account/signin/check
           #logout:
           #   path:   /public/account/signout
           #   target: /welcome

    access_control:
        - { path: ^/welcome, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/public,  roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/tourn,   roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin,   roles: ROLE_ADMIN }
        - { path: ^/user,    roles: ROLE_USER }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
