# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
    
# National Games Routes
zayso_core_index:
    pattern:  /
    defaults: { _controller: ZaysoNatGamesBundle:Welcome:welcome }

zayso_natgames_welcome:
    pattern:  /welcome
    defaults: { _controller: ZaysoNatGamesBundle:Welcome:welcome }
    
zayso_core_welcome:
    pattern:  /welcome
    defaults: { _controller: ZaysoNatGamesBundle:Welcome:welcome }

# Used when user is not authorized
zayso_core_welcomex:
    pattern:  /welcome
    defaults: { _controller: ZaysoNatGamesBundle:Welcome:welcome }

zayso_core_textalerts:
    pattern:  /welcome/textalerts
    defaults: { _controller: ZaysoNatGamesBundle:Welcome:textalerts }
    
zayso_core_contact:
    pattern:  /welcome/contact
    defaults: { _controller: ZaysoNatGamesBundle:Welcome:contact }
    
zayso_core_contact_org:
    pattern:  /contact
    defaults: { _controller: ZaysoNatGamesBundle:Welcome:contact }
    
zayso_core_classes:
    pattern:  /welcome/classes
    defaults: { _controller: ZaysoNatGamesBundle:Classes:signup }
    
zayso_core_classes_org:
    pattern:  /classes
    defaults: { _controller: ZaysoNatGamesBundle:Classes:signup }

# Home stuff requires user
zayso_core_home:
    pattern:  /home
    defaults: { _controller: ZaysoNatGamesBundle:Home:index }
    
zayso_core_project_plans:
    pattern:  /home/person/project/plans/{id}
    defaults: { _controller: ZaysoNatGamesBundle:Project:plans, id: 0 }
    requirements:
        id: \d+
        
zayso_core_project_levels:
    pattern:  /home/person/project/levels{id}
    defaults: { _controller: ZaysoNatGamesBundle:Project:levels, id: 0 }
    requirements:
        id: \d+
    
zayso_natgames_home:
    pattern:  /home
    defaults: { _controller: ZaysoNatGamesBundle:Home:index }

# ===============================================================
# Account stuff
zayso_natgames_account_create:
    pattern:  /account/create
    defaults: { _controller: ZaysoNatGamesBundle:Account\Create:create }

zayso_natgames_account_profile:
    pattern:  /account/profile
    defaults: { _controller: ZaysoNatGamesBundle:Account\Profile:index }
    requirements:
        _method:  GET

zayso_natgames_account_profile_post:
    pattern:  /account/profile
    defaults: { _controller: ZaysoNatGamesBundle:Account\Profile:post }
    requirements:
        _method:  POST

zayso_core_account_edit:
    pattern:  /account/edit/{id}
    defaults: { _controller: ZaysoNatGamesBundle:Account\Edit:edit, id: 0}
    requirements:
        id: \d+
        
zayso_natgames_account_reset:
    pattern:  /account/reset/{id}
    defaults: { _controller: ZaysoNatGamesBundle:Account\Signin:reset, id: 0}
    requirements:
        id: \d+
        
zayso_natgames_account_resetx:
    pattern:  /account/resetx/{reset}
    defaults: { _controller: ZaysoNatGamesBundle:Account\Signin:resetx, reset: 0}

zayso_natgames_account_signin:
    pattern:  /account/signin
    defaults: { _controller: ZaysoNatGamesBundle:Account\Signin:signin }

zayso_natgames_account_signin_rpx:
    pattern:  /account/signin/rpx
    defaults: { _controller: ZaysoNatGamesBundle:Account\Signin:signinRpx }

zayso_natgames_account_signout:
    pattern:  /account/signout
    defaults: { _controller: ZaysoNatGamesBundle:Account\Signin:signout }

zayso_core_account_openid_add:
    pattern:  /account/openid/add
    defaults: { _controller: ZaysoNatGamesBundle:Account\Openid:add }

zayso_core_account_openid_add_rpx:
    pattern:  /account/openid/add/rpx
    defaults: { _controller: ZaysoNatGamesBundle:Account\Openid:addRpx }

zayso_core_account_person_add:
    pattern:  /account/person/add
    defaults: { _controller: ZaysoNatGamesBundle:Account\Person:add }
    
zayso_core_account_person_edit:
    pattern:  /account/person/edit/{id}
    defaults: { _controller: ZaysoNatGamesBundle:Account\Person:edit, id: 0 }
    requirements:
        id: \d+

# =================================================================
# Scheduling stuff

zayso_core_person_team_list:
    pattern:  /home/person/team/list/{personId}
    defaults: { _controller: ZaysoNatGamesBundle:Person\Team:list, personId: 0 }
    requirements:
        personId: \d+

zayso_core_schedule:
    pattern:  /schedule/public
    defaults: { _controller: ZaysoNatGamesBundle:Schedule:index }
    requirements:
        _method:  GET

# =================================================
# Admin stuff
zayso_natgames_admin:
    pattern:  /admin
    defaults: { _controller: ZaysoNatGamesBundle:Admin\Admin:index }
    requirements:
        _method:  GET

zayso_natgames_admin_account_edit:
    pattern:  /admin/account/edit/{id}
    defaults: { _controller: ZaysoNatGamesBundle:Admin\Account\Edit:edit, id: 0}
    requirements:
        id: \d+
        
zayso_natgames_admin_account_list:
    pattern:  /admin/account/list.{_format}
    defaults: { _controller: ZaysoNatGamesBundle:Admin\Account\List:list, _format: html }
    requirements:
        _method:  GET
        _format:  html|csv
        
zayso_natgames_admin_person_list:
    pattern:  /admin/person/list.{_format}
    defaults: { _controller: ZaysoNatGamesBundle:Admin\Person\List:list, _format: html }
    requirements:
        _method:  GET
        _format:  html|csv|xls

zayso_natgames_admin_import:
    pattern:  /admin/import
    defaults: { _controller: ZaysoNatGamesBundle:Admin\Import:index }
