imports:
    - { resource: setup.ini }
    - { resource: parameters.ini }
    - { resource: session.yml }
    - { resource: security.yml }
    - { resource: doctrine.yml }
 
framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig','php'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true
        lifetime:       66600000
        name:           zaysoNatGames2012
        storage_id:     zayso_core.session.storage

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        janrain_token_route: 'zayso_natgames_account_signin_rpx'
        myBundleName:        %my_bundle_name%
        myTitlePrefix:       %my_title_prefix%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false
