## Session Storage area stuff

# Session class and database schema info
parameters:
    session.class: Zayso\Osso2007Bundle\Component\Session

## Not using these but keep as an example
    pdo.db_options:
        db_table:    session_data
        db_id_col:   session_id
        db_data_col: session_value
        db_time_col: session_time

## My ver own services!!!
services:
  
    session.storage.mine:
        class:     Zayso\Osso2007Bundle\Component\SessionStorage
        arguments: [@session.pdo, %session.storage.options%, %pdo.db_options%]
  
    session.pdo:
        class: PDO
        arguments:
            dsn:      %session_dsn%
            user:     %database_user%
            password: %database_password%
            
framework:
    session:
        default_locale: %locale%
        auto_start:     true
        name:           osso2007
        storage_id:     session.storage.mine
