Zayso\Osso2007Bundle\Entity\EventClass:
  type: entity
  table: event_class
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    key1:
      type: string
      length: 10
      fixed: true
      nullable: false
    desc1:
      type: string
      length: 80
      fixed: true
      nullable: true
  lifecycleCallbacks: {  }
