Zayso\Osso2007Bundle\Entity\PhoneDoctrine:
  type: entity
  table: phone_doctrine
  fields:
    phoneId:
      id: true
      type: bigint
      nullable: false
      column: phone_id
      generator:
        strategy: IDENTITY
    phoneTypeId:
      type: bigint
      nullable: true
      column: phone_type_id
    personId:
      type: bigint
      nullable: true
      column: person_id
    areaCode:
      type: string
      length: 4
      fixed: false
      nullable: true
      column: area_code
    num:
      type: string
      length: 8
      fixed: false
      nullable: true
    ext:
      type: string
      length: 8
      fixed: false
      nullable: true
  lifecycleCallbacks: {  }
