Zayso\Osso2007Bundle\Entity\EventPersonType:
  type: entity
  table: event_person_type
  fields:
    eventPersonTypeId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: event_person_type_id
      generator:
        strategy: IDENTITY
    keyx:
      type: string
      length: 4
      fixed: true
      nullable: true
    descx:
      type: string
      length: 20
      fixed: true
      nullable: true
  lifecycleCallbacks: {  }
