# Doctrine Configuration
#doctrine:
#    dbal:
#        driver:   %database_driver%
#        host:     %database_host%
#        port:     %database_port%
#        dbname:   %database_name%
#        user:     %database_user%
#        password: %database_password%
#        charset:  UTF8

#    orm:
#        auto_generate_proxy_classes: %kernel.debug%
#        auto_mapping: true

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8

            eayso:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_eayso_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8

            osso2007:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_osso2007_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
                
            osso2012:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_osso2012_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8

    orm:
        default_entity_manager:   default
        auto_generate_proxy_classes: %kernel.debug%
#       auto_mapping: true
        entity_managers:
            default:
                connection: default
                mappings:
                    ZaysoBundle: ~
            eayso:
                connection: eayso
                mappings:
                    EaysoBundle: ~
            osso2007:
                connection: osso2007
                mappings:
                    Osso2007Bundle: ~
            osso2012:
                connection: osso2012
                mappings:
                    ZaysoBundle: ~

