# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

_zayso_welcome:
    pattern:  /
    defaults: { _controller: ZaysoBundle:Welcome:welcome }
    
# National Games Routes
_natgames_welcome:
    pattern:  /natgames
    defaults: { _controller: NatGamesBundle:Welcome:welcome }
    
_natgames_home:
    pattern:  /natgames/home
    defaults: { _controller: NatGamesBundle:Welcome:home }
    
_natgames_welcomex:
    pattern:  /natgames/welcome
    defaults: { _controller: NatGamesBundle:Welcome:welcome }
    
_natgames_form:
    pattern:  /natgames/form
    defaults: { _controller: NatGamesBundle:Form:form }

_natgames_contact:
    pattern:  /natgames/contact
    defaults: { _controller: NatGamesBundle:Contact:contact }
    
_natgames_account_create:
    pattern:  /natgames/account/create
    defaults: { _controller: NatGamesBundle:Account\Edit:create }
        
_natgames_account_create_post:
    pattern:  /natgames/account/create
    defaults: { _controller: NatGamesBundle:Account\Edit:createPost }
    requirements:
        _method:  POST
    
_natgames_account_signin:
    pattern:  /natgames/account/signin
    defaults: { _controller: NatGamesBundle:Account:signin }
    requirements:
        _method:  GET

_natgames_account_signin_post:
    pattern:  /natgames/account/signin
    defaults: { _controller: NatGamesBundle:Account:signinPost }
    requirements:
        _method:  POST

_natgames_account_signout:
    pattern:  /natgames/account/signout
    defaults: { _controller: NatGamesBundle:Account:signout }

# Project Person Information
_natgames_project_plans:
    pattern:  /natgames/project/plans
    defaults: { _controller: NatGamesBundle:Project:plans }
    requirements:
        _method:  GET

_natgames_project_plans_post:
    pattern:  /natgames/project/plans
    defaults: { _controller: NatGamesBundle:Project:plansPost }
    requirements:
        _method:  POST

_natgames_project_levels:
    pattern:  /natgames/project/levels
    defaults: { _controller: NatGamesBundle:Project:levels }
    requirements:
        _method:  GET

_natgames_project_levels_post:
    pattern:  /natgames/project/levels
    defaults: { _controller: NatGamesBundle:Project:levelsPost }
    requirements:
        _method:  POST

_natgames_schedule:
    pattern:  /natgames/schedule
    defaults: { _controller: NatGamesBundle:Schedule:index }
    requirements:
        _method:  GET

# =================================================
# Admin stuff
_natgames_admin:
    pattern:  /natgames/admin
    defaults: { _controller: NatGamesBundle:Admin:index }
    requirements:
        _method:  GET
        
_natgames_admin_accounts:
    pattern:  /natgames/admin/accounts.{_format}
    defaults: { _controller: NatGamesBundle:Admin:accounts, _format: html }
    requirements:
        _method:  GET
        _format:  html|csv

_natgames_admin_import:
    pattern:  /natgames/admin/import
    defaults: { _controller: NatGamesBundle:Admin\Import:index }

# resource: routing_area5cf.yml
_main:
    resource: routing_area5cf.yml
    
    