Zayso\Osso2007Bundle\Entity\EmailType:
  type: entity
  table: email_type
  fields:
    emailTypeId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: email_type_id
      generator:
        strategy: IDENTITY
    descx:
      type: string
      length: 8
      fixed: true
      nullable: true
  lifecycleCallbacks: {  }
