Zayso\Osso2007Bundle\Entity\Event:
  type: entity
  table: event
  fields:
    eventId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: event_id
      generator:
        strategy: IDENTITY
    eventNum:
      type: integer
      unsigned: false
      nullable: true
      column: event_num
    projectId:
      type: integer
      unsigned: false
      nullable: true
      column: project_id
    regYearId:
      type: integer
      unsigned: false
      nullable: true
      column: reg_year_id
    seasonTypeId:
      type: integer
      unsigned: false
      nullable: true
      column: season_type_id
    scheduleTypeId:
      type: integer
      unsigned: false
      nullable: true
      column: schedule_type_id
    eventTypeId:
      type: integer
      unsigned: false
      nullable: true
      column: event_type_id
    classId:
      type: integer
      unsigned: false
      nullable: true
      column: class_id
    unitId:
      type: integer
      unsigned: false
      nullable: true
      column: unit_id
    status:
      type: integer
      unsigned: false
      nullable: true
    fieldId:
      type: integer
      unsigned: false
      nullable: true
      column: field_id
    eventDate:
      type: string
      length: 8
      fixed: true
      nullable: true
      column: event_date
    eventTime:
      type: string
      length: 4
      fixed: true
      nullable: true
      column: event_time
    eventDuration:
      type: integer
      unsigned: false
      nullable: true
      column: event_duration
    point1:
      type: integer
      unsigned: false
      nullable: false
    point2:
      type: integer
      unsigned: false
      nullable: false
  lifecycleCallbacks: {  }
