Zayso\Osso2007Bundle\Entity\FamilyTeam:
  type: entity
  table: family_team
  fields:
    familyTeamId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: family_team_id
      generator:
        strategy: IDENTITY
    familyId:
      type: integer
      unsigned: false
      nullable: true
      column: family_id
    teamId:
      type: integer
      unsigned: false
      nullable: true
      column: team_id
    familyTeamTypeId:
      type: integer
      unsigned: false
      nullable: true
      column: family_team_type_id
  lifecycleCallbacks: {  }
