Zayso\Osso2007Bundle\Entity\FieldSite:
  type: entity
  table: field_site
  fields:
    fieldSiteId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: field_site_id
      generator:
        strategy: IDENTITY
    unitId:
      type: integer
      unsigned: false
      nullable: true
      column: unit_id
    keyx:
      type: string
      length: 20
      fixed: true
      nullable: true
    sortx:
      type: string
      length: 10
      fixed: true
      nullable: true
    descx:
      type: string
      length: 20
      fixed: true
      nullable: true
  lifecycleCallbacks: {  }
