Zayso\Osso2007Bundle\Entity\PhoneType:
  type: entity
  table: phone_type
  fields:
    phoneTypeId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: phone_type_id
      generator:
        strategy: IDENTITY
    descx:
      type: string
      length: 8
      fixed: true
      nullable: true
  lifecycleCallbacks: {  }
