Zayso\Osso2007Bundle\Entity\UnitType:
  type: entity
  table: unit_type
  fields:
    unitTypeId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: unit_type_id
      generator:
        strategy: IDENTITY
    descx:
      type: string
      length: 20
      fixed: true
      nullable: true
  lifecycleCallbacks: {  }
